### ISSUE TITLE
can't tangle sockets.w

### ISSUE THREAD

**Issue by fedeinthemix** [arcfide/chez-sockets#5]
Hi,

I'm trying to use chez-sockets with Chez Scheme 9.4. I have successfully compiled ChezWEB 2.0, but it looks like it can't process sockets.w. I get the following error:

$ cheztangle sockets.w
This is CHEZTANGLE, ChezWEB Version 2.0.
Exception: Unexpected token with irritants (" () \n     =>\n
(internet-address->foreign foreign->internet-address)\n" \x40;<)

**Comment by arcfide** [comment]
I can't tell if you are the same who emailed me, but I'll include my response here as well:

Thank you for your interest in my Sockets library and I'm sorry that you're
having trouble with things. I'm afraid that I haven't been keeping up in the
Scheme world lately and so I've let a few of my programs go. I guess I didn't
expect a new version of Chez Scheme to be released!

I'm trying to carve out some time to take a look at your ChezWEB problem, as
that shouldn't be happening, but I'm not sure if I will have much time to
dig into the FFI and really get some ideas on what changes need to be made to
make things work. There's no reason it shouldn't work with the new 9.4 using
the old FFI if the old FFI is still around, but if there is new FFI machinery,
I would definitely prefer to use that over the old. The WEB document should
give you most of the details on how to get the sockets working and how I
map things down. Really it should be somewhat trivial to figure out how to
map the old FFI concepts to the new, which should get you everything you want.

I would love for you to make a pull request with the updates to the FFI if you
make them. I think there may have been something that changed in the reader
for Chez Scheme that makes things not work for you in ChezWEB, so I'll see if
I can hunt that down.

**Comment by fedeinthemix** [comment]
Hi again!

After much frustration I restarted from clean checkouts for both
ChezWEB and chez-sockets. By passing '--tex=tex' to mpost now
everything works and I can build chez-sockets! I guess I just messed
up things by trying '--tex=xetex', ...

Sorry for the noise!

**Comment by fedeinthemix** [comment]
Now, I can tangle sockets.w and compile the generated C files.
However, when I try to import the library I get the following error:

$ scheme
Chez Scheme Version 9.4
Copyright 1984-2016 Cisco Systems, Inc.

> (import (arcfide sockets))
Exception: invalid syntax #<void> at line 876, char 56 of arcfide/sockets.ss
Type (debug) to enter the debugger.

**Comment by arcfide** [comment]
Okay, thanks for the report. I've fixed this up, since it was an issue with a slight change in handling the machine code that creeped in while working on supporting non-threaded stuff. I've just pushed changes to this that should have you loading up sockets without trouble. You can do it to ways. You can use the sockets.sls file to load the library version of things, or you should be able to directly `LOAD` the sockets.ss file. Please let me know if this fixes the issues. Also, please check the sockets.pdf file that should be produced when you use the Makefile and ensure that things look good there, as that's the primary documentation for the whole system.

**Comment by arcfide** [comment]
Also, thanks for your interest in the sockets library! Pull requests to improve documentation, formatting, presentation, capabilities, and elegance are all welcome.

**Comment by fedeinthemix** [comment]
I can confirm that I can now successfully import the library. The
documentation is also built successfully. Now on to study how to use it ;-)

Thank you very much for your great support!

**Comment by arcfide** [comment]
Great, I'll close this issue and if you have any further problems, please open a new issue with the new problems. Good luck, and I hope everything goes well!
